baseurl = "https://apurvanakade.github.io/blog/"
languageCode = "en"
contentDir = "content"
paginate = 15
publishDir = "docs"
buildDrafts = false

canonifyURLs = true
relativeURLs = true

title = "PostDoc Problems"
theme = "ApurvasTheme"

[taxonomies]
  tag = "tags"

[author]
  name = "Apurva Nakade"

[markup.goldmark.renderer]
  unsafe = true
